name: Build Labio APK with Buildozer

on:
  push:
    branches:
      - main  # Запускать сборку при каждом пуше в ветку main
  workflow_dispatch: # Позволяет запускать сборку вручную из вкладки Actions

jobs:
  build:
    runs-on: ubuntu-22.04 # Используем стабильный Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Buildozer global directory
        uses: actions/cache@v3
        with:
          path: ~/.buildozer
          key: ${{ runner.os }}-buildozer-global-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-buildozer-global-

      - name: Cache Buildozer project directory
        uses: actions/cache@v3
        with:
          path: .buildozer
          key: ${{ runner.os }}-buildozer-project-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-buildozer-project-

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          pip3 install --user --upgrade buildozer cython requests

      - name: Build APK with Buildozer
        run: |
          export PATH=$PATH:$HOME/.local/bin
          buildozer android debug
        # Чтобы собрать релизную версию (нужны ключи), замените debug на release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: Labio-Messenger-Debug-APK
          path: b
          in/*.apk
